### ISSUE TITLE
What Happen Bro

### ISSUE THREAD

**Issue by AidenHeavensSSS** [Maseshi/Shioru#119]
C:\Users\Administrator\Desktop\Shioru>node ./source/shard.js

  ███████╗██╗  ██╗██╗ ██████╗ ██████╗ ██╗   ██╗  v
  ██╔════╝██║  ██║██║██╔═══██╗██╔══██╗██║   ██║  3
  ███████╗███████║██║██║   ██║██████╔╝██║   ██║  .
  ╚════██║██╔══██║██║██║   ██║██╔══██╗██║   ██║  6
  ███████║██║  ██║██║╚██████╔╝██║  ██║╚██████╔╝  .
  ╚══════╝╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝   4

Copyright (C) 2020-2024 Chaiwat Suwannarat. All rights reserved.
Website: https://shiorus.web.app/, License: MIT & CC0-1.0
C:\Users\Administrator\Desktop\Shioru\node_modules\discord.js\src\util\Util.js:69
  if (!token) throw new DiscordjsError(ErrorCodes.TokenMissing);
                    ^

Error [TokenMissing]: Request to use token, but token was unavailable to the client.
    at fetchRecommendedShardCount (C:\Users\Administrator\Desktop\Shioru\node_modules\discord.js\src\util\Util.js:69:21)
    at ShardingManager.spawn (C:\Users\Administrator\Desktop\Shioru\node_modules\discord.js\src\sharding\ShardingManager.js:197:22)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\Shioru\source\shard.js:302:9)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'TokenMissing'
}

Node.js v20.15.0
![Capture](https://github.com/Maseshi/Shioru/assets/165247047/95d42b73-1a48-4649-b62c-facd96e86275)
![Capture1](https://github.com/Maseshi/Shioru/assets/165247047/0b75f973-5512-4c90-abeb-8e9d097efcea)

**Comment by Maseshi** [comment]
`[TokenMissing]` It is saying that you have not set any environment variables in the project. Check to see if there is a file named **.env** in your project. If not, rename the file **.env.example** to **.env** and add the necessary variables.
https://github.com/Maseshi/Shioru?tab=readme-ov-file#-installation

**Comment by AidenHeavensSSS** [comment]
![image](https://github.com/Maseshi/Shioru/assets/165247047/504c7ca5-cd80-45d2-a2bc-64fde573327c)
But i will change requirement to .env

and when i use command npm install --global --production --add-python-to-path windows-build-tools
is error 
![image](https://github.com/Maseshi/Shioru/assets/165247047/e6f9139e-aa6a-49b6-b8b9-b8d152c39166)

**Comment by Maseshi** [comment]
Try running the script as administrator. If you still can't install it, you can still choose to install it through the Node.js installer.
https://raw.githubusercontent.com/Maseshi/Shioru/main/assets/images/node-js-tools-for-native-modules.png

**Comment by AidenHeavensSSS** [comment]
![image](https://github.com/Maseshi/Shioru/assets/165247047/640aa8c4-53eb-450c-9a89-e0879fec812b)
i will reinstall node js and tick Tool for Native Modules 
my dc : aiden_heavens

**Comment by Maseshi** [comment]
[Uninstall Chocolatey](https://docs.chocolatey.org/en-us/choco/uninstallation/) and setup tools for native modules again. The script is located in the `C:\Program Files\nodejs` folder if you have not installed it anywhere else.

**Comment by breladetm** [comment]
The exact same issue here. Followed the steps given by Masheshi to no avail.

**Comment by Maseshi** [comment]
> The exact same issue here. Followed the steps given by Masheshi to no avail. 

There are several ways to install **Visual Studio Build Tools**. I have tried to improve the documentation on installing this tool. But the way I installed this tool is by downloading it from the Visual Studio website under ![Build Tools for Visual Studio 2022](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2022) and then within the installer select **Desktop development with C++** or choose to download the full version that includes the IDE as well.

**Comment by Maseshi** [comment]
Have you changed the file from `.env.example` to `.env`?

**Comment by AidenHeavensSSS** [comment]
yes im rename it 
![image](https://github.com/user-attachments/assets/c43f2599-549a-4940-a2bf-f70c3431eb2a)

**Comment by Maseshi** [comment]
What script do you run the command with?  `npm start`?

**Comment by Maseshi** [comment]
> using `node --env-file .env ./source/shard.js` would fix the problem mentioned above i believe

In your folder you must have a **.env** file copied and renamed from [.env.example](https://github.com/Maseshi/Shioru/blob/57ea389f1c2aea26975467fa611ca04901777bf3/.env.example) and you must add your bot token to `TOKEN=` for it to work.
