### ISSUE TITLE
I think it's not working...

### ISSUE THREAD

**Issue by mrgoonie** [Maseshi/Shioru#40]
I added the bot to my server and tried some commands but it didn't respond..

![image](https://github.com/Maseshi/Shioru/assets/6857382/01d61c8a-2c0a-47d1-b251-292f5d51082d)

**Comment by Maseshi** [comment]
Thank you for reporting your problem.  I've found the cause of this problem and will be working on fixing it temporarily soon. I'll let you know again if it's fixed.
