### ISSUE TITLE
What is %s?

### ISSUE THREAD

**Issue by IFlox** [Maseshi/Shioru#47]
I don't understand what is %s in your project as I am new to this field and I am seeing it a lot in your code. As I searched through the files I am not ables see it as a variable or anything. If you can please tell me how does it work or anything.

**Comment by Maseshi** [comment]
I got this inspiration from Minecraft project https://github.com/Mojang/bedrock-samples/blob/60083d4b1d4a62bc88f71636a23992b750d659d1/resource_pack/texts/en_US.lang#L14.

`%s` is a replacement for some value. In fact, it can represent anything other than `%s` such as `%n`, `%number` or `%string`. Any value other than `%s` must replace itself, for example:
```Javascript
// Javascript
const name = "John";
const text = "Hello, my name is %s";

text.replace("%s", name);
console.log(text);
// -> Hello, my name is John
```
By using **%s** helps I can translate more easily.

**Comment by Maseshi** [comment]
If you are still confused, you can compare between these two files of mine.
https://github.com/Maseshi/Shioru/blob/9c4093482d52a8002fc45d6ca8f52873789583c8/source/commands/developer/ping.js#L33-L35
https://github.com/Maseshi/Shioru/blob/9c4093482d52a8002fc45d6ca8f52873789583c8/source/languages/en-US.json#L392

**Comment by IFlox** [comment]
Alright 👍, now I understand it. Thanks for the help.
