### ISSUE TITLE
Hi how to fix this

### ISSUE THREAD

**Issue by Quinnzy** [Maseshi/Shioru#72]
I host the bot on a host and got this error
![Screenshot_2023_0820_084340](https://github.com/Maseshi/Shioru/assets/142702497/9aeb7da6-7997-42ea-a634-873868475b35)
![Screenshot_2023_0820_084450](https://github.com/Maseshi/Shioru/assets/142702497/976367a8-a993-4285-a75a-4d3f1203cfa1)
![Screenshot_2023_0820_084502](https://github.com/Maseshi/Shioru/assets/142702497/a4e11bac-0fcd-4c3a-a6da-aa10b21212ed)

**Comment by Maseshi** [comment]
The server seems to have incompletely installed the dependency.  If possible, try deleting the **node_modules** folder and reinstalling all the dependency again.
```sh
# Linux
# Delete the node_modules folder.
sudo rm -r node_modules
```
then
```sh
npm install
```

**Comment by Quinnzy** [comment]
> The server seems to have incompletely installed the dependency. If possible, try deleting the **node_modules** folder and reinstalling all the dependency again. If you are using a container, try creating a new one.
> 
> ```shell
> # Linux
> # Delete the node_modules folder.
> sudo rm -r node_modules
> ```
> 
> then
> 
> ```shell
> npm install
> ```

You know how to do that on a pterodactyl panel ?

**Comment by Maseshi** [comment]
> > The server seems to have incompletely installed the dependency. If possible, try deleting the **node_modules** folder and reinstalling all the dependency again. If you are using a container, try creating a new one.
> > 
> > ```shell
> > # Linux
> > # Delete the node_modules folder.
> > sudo rm -r node_modules
> > ```
> > 
> > then
> > 
> > ```shell
> > npm install
> > ```
> 
> You know how to do that on a pterodactyl panel ?

I see from your screenshot there is a command line in it.  So try running this command on the command line to delete.  **node_modules** and reinstall the depandancies.
```sh
# Delete the node_modules folder.
sudo rm -r /home/container/node_modules
```
then
```sh
npm install
```
If you can't delete I recommend doing a google search for how to manage files on the server.

**Comment by Quinnzy** [comment]
> > The server seems to have incompletely installed the dependency. If possible, try deleting the **node_modules** folder and reinstalling all the dependency again. If you are using a container, try creating a new one.
> > ```shell
> > # Linux
> > # Delete the node_modules folder.
> > sudo rm -r node_modules
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then
> > ```shell
> > npm install
> > ```
> 
> You know how to do that on a pterodactyl panel ?

I cant do that right there but ill try to fix that, thank you btw :d
