### ISSUE TITLE
Webhook Feature

### ISSUE THREAD

**Issue by Quinnzy** [Maseshi/Shioru#76]
### Can you add a webhook feature?
Some lines in .env like:

SERVER_LOGS_WEBHOOK - send the webhook when the bot joins a server

ISSUE_WEBHOOK - people will use /issue command with the bug and attachment (if possible) and the issue will send to the webhook

And some more webhooks like in [this repo](https://github.com/CorwinDev/Discord-Bot/blob/main/src/config/webhooks.json)

**Comment by Maseshi** [comment]
Looks like a good idea, I'm planning on doing this as well.
So I think it might take some time to create webhooks to update things. I agree with your proposal.

Thank you for the recommendation.

**Comment by Quinnzy** [comment]
> Looks like a good idea, I'm planning on doing this as well. So I think it might take some time to create webhooks to update things. I agree with your proposal.
> 
> Thank you for the recommendation.

You're welcome, keep improving your bot :)
