### ISSUE TITLE
Cloud Firestore API | Firebase GrpcConnection RPC

### ISSUE THREAD

**Issue by ivAkii** [Maseshi/Shioru#78]
Cloud Firestore API issue after enabling it 
**Error Code**
```
   [2023-10-03T12:37:22.649Z]  @firebase/firestore: Firestore (10.4.0): GrpcConnection RPC 'Write' stream 0x61b847fe error. Code: 5 Message: 5 NOT_FOUND:
```

**Comment by Maseshi** [comment]
Do you have a full bug report?

**Comment by Maseshi** [comment]
Do you have a full bug report?

**Comment by ivAkii** [comment]
![image](https://github.com/Maseshi/Shioru/assets/74487183/bb2f73a7-06bb-4201-ab5b-7b54c4ecdcd3)

Unfortunately that was the only line of error code as you can see.
But that doesn't mean the bot don't work tho Haha.
I'm just curious of the cause of this error

**Comment by Maseshi** [comment]
>  Cloud Firestore API issue after enabling it 
> **Error Code**
> ```
>    [2023-10-03T12:37:22.649Z]  @firebase/firestore: Firestore (10.4.0): GrpcConnection RPC 'Write' stream 0x61b847fe error. Code: 5 Message: 5 NOT_FOUND:
> ```
> 

Have you set your Firestore rules to [test mode](https://firebase.google.com/docs/firestore/quickstart?hl=th#secure_your_data)?

**Comment by Maseshi** [comment]
> ![image](https://github.com/Maseshi/Shioru/assets/74487183/bb2f73a7-06bb-4201-ab5b-7b54c4ecdcd3)
> 
> Unfortunately that was the only line of error code as you can see.
> But that doesn't mean the bot don't work tho Haha.
> I'm just curious of the cause of this error.
> 
> EDIT: 
> I forgot to mention that even tho the commands work this is the error log
> 
> ![image](https://github.com/Maseshi/Shioru/assets/74487183/91164b8a-60ac-4f7c-84ba-23a4983f7597)
> 

I have seen this bug and will fix it with the next version. Thanks 😊.

**Comment by Maseshi** [comment]
>  Cloud Firestore API issue after enabling it 
> **Error Code**
> ```
>    [2023-10-03T12:37:22.649Z]  @firebase/firestore: Firestore (10.4.0): GrpcConnection RPC 'Write' stream 0x61b847fe error. Code: 5 Message: 5 NOT_FOUND:
> ```
> 

Have you set your Firestore rules to [test mode](https://firebase.google.com/docs/firestore/quickstart?hl=th#secure_your_data)?

**Comment by ivAkii** [comment]
Thank youuu It was in production mode Haha
